spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 568888ed33e3772bd891
            clientSecret: 8c937699985b06e17d116d4f10525bcf6144999f
# ...